MostiSubject_MVC_Board/Models/Board.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MostiSubject_MVC_Board.Models
{
    /// <summary>
    /// Board
    /// 게시판 원본 Model
    /// </summary>
    public class Board
    {
        // 테이블 데이터
        // 아이디, 제목, 내용, 조회수, 생성일, 작성자, 삭제여부, 행번호, file객체, fileName

        public int board_id { get; set; }

        [Display(Name = "제목")]
        [Required(ErrorMessage = "제목을 입력해주세요")]
        [StringLength(300, ErrorMessage = "제목은 300자를 넘을 수 없습니다.")]
        public string title { get; set; }

        [Display(Name = "내용")]
        [Required(ErrorMessage = "내용을 입력해주세요")]
        [StringLength(8000, ErrorMessage = "내용은 8000자를 넘을 수 없습니다.")]
        public string content { get; set; }

        
        public int hitCount { get; set; }

        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime board_date { get; set; }

        [Display(Name = "작성자")]
        [Required(ErrorMessage = "ID가 필요합니다.")]
        [StringLength(200, ErrorMessage = "ID 는 200자를 넘을 수 없습니다.")]
        public string u_id { get; set; }

        public int del_check { get; set; }
    
        public int rownum { get; set; }


        public HttpPostedFileBase files { get; set; }

        public string fileName { get; set; }

    }
}

MostiSubject_MVC_Board/Controllers/BoardController.cs
using MostiSubject_MVC_Board.DataBase.Task;
using MostiSubject_MVC_Board.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using MostiSubject_MVC_Board.DataBase.Util;

namespace MostiSubject_MVC_Board.Controllers
{
    public class BoardController : Controller
    {

        /// <summary>
        /// Search()
        /// 검색 후 List 액션을 Redirect 하는 액션
        /// </summary>
        /// <param name="boardRequest"></param>
        /// <returns></returns>
        [HttpGet]
        [ActionName("Search")]
        public ActionResult Search(BoardRequest boardRequest)
        {

            return RedirectToAction("List", boardRequest);
        }


        /// <summary>
        /// List()
        /// 게시물 전체 내용이 출력되는 액션
        /// </summary>
        /// <param name="boardRequest"></param>
        /// <returns></returns>
        #region List()
        [ActionName("List")]
        [HttpGet]
        public ActionResult List(BoardRequest boardRequest, int? page)
        {
            // dao 객체 생성
            BoardDAO dao = new BoardDAO();

            // 검색 값 유지
            if (boardRequest.search_type != null && boardRequest.search_word != null)
            {
                ViewBag.search_type = boardRequest.search_type;
                ViewBag.search_word = boardRequest.search_word;
            }

            // page 설정
            int pageSize = 10;
            int pageNumber = page ?? 1;
            ViewBag.pageNumber = pageNumber;

            // boardList 추출
            List<Board> boardList = dao.ReadBoard(boardRequest);

            // response 객체 생성 후 List 에 담기
            BoardResponse boardResponse = new BoardResponse()
            {
                BoardList = boardList
                , PageList = boardList.ToPagedList(pageNumber, pageSize)

            };

            // View 에 Model 을 담아 이동
            return View(boardResponse.PageList);
        }
        #endregion



        


        /// <summary>
        /// Create()
        /// 게시물 작성 View 로 이동하는 액션
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        #region Create()
        public ActionResult Create(BoardRequest boardRequest, string page)
        {
            // 검색 값 유지
            if (boardRequest.search_type != null && boardRequest.search_word != null)
            {
                ViewBag.search_type = boardRequest.search_type;
                ViewBag.search_word = boardRequest.search_word;
            }

            // 페이지 유지
            ViewBag.pageNumber = page ?? "1";

            return View();
        }
        #endregion


        /// <summary>
        /// Create()
        /// 게시물 입력을 수행하는 액션
        /// </summary>
        /// <param name="board"></param>
        /// <returns></returns>
        #region Create(Board board)
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Board board)
        {
            // 모델이 유효하지 않다면
            if (!ModelState.IsValid)
            {
                // 해당 뷰로 다시 돌아간다.
                return View();
            }


            // ▼ 게시물 입력수행
            int result = 0;
            BoardDAO dao = new BoardDAO();


            try
            {
                result = dao.CreateBoard(board);

                if (result > 0)
                    return RedirectToAction("List");
                else
                {
                    ViewBag.errMsg = "알 수 없는 오류로 인해 게시물 작성에 실패했습니다. 다시 돌아가서 작성해주세요";
                    return View("Errors");
                }
            }
            catch (Exception ex)
            {
                string errMsg = ex.ToString();
                ViewBag.errMsg = errMsg;
                return View("Errors");
            }

        }
        #endregion

        /// <summary>
        /// Detail(string board_id, string page)
        /// 게시물 상세 페이지로 진입하는 액션
        /// HttpGet 으로 진입한 경우에 수행
        /// </summary>
        /// <param name="board_id"></param>
        /// <param name="page"></param>
        /// <returns></returns>
        #region Detail(string board_id, string page)
        [ActionName("Detail")]
        [HttpGet]
        public ActionResult Detail(string board_id, string page, BoardRequest boardRequest)
        {
            // 페이지 유지
            if (string.IsNullOrEmpty(page))
                page = "1";

            ViewBag.pageNumber = page;

            // 검색 값 유지
            if (boardRequest.search_type != null && boardRequest.search_word != null)
            {
                ViewBag.search_type = boardRequest.search_type;
                ViewBag.search_word = boardRequest.search_word;
            }

            BoardDAO dao = new BoardDAO();
            BoardResponse response = new BoardResponse();


            response.boardDetail = dao.ReadBoard(int.Parse(board_id));
            response.page = int.Parse(page);

            return View("Detail", response);
        }
        #endregion


        /// <summary>
        /// Detail(string fileName)
        /// 게시물 상세페이지에서 file을 다운로드하는 액션
        /// HttpPost 로 진입한 경우에 수행
        /// </summary>
        /// <param name="fileName"></param>
        #region Detail(string fileName)
        [ActionName("Detail")]
        [HttpPost]
        public void Detail(string fileName)
        {
            // HttpContext 객체 생성
            HttpContext context = System.Web.HttpContext.Current;

            FileSystem fs = new FileSystem();

            // 현재 페이지에서 다운로드 수행
            fs.ProcessRequest(context);

        }
        #endregion

        /// <summary>
        /// Update(string board_id, string page, BoardRequest boardRequest)
        /// 게시물 수정 View 로 이동하는 액션
        /// HttpGet 으로 진입한 경우에 수행
        /// </summary>
        /// <param name="board_id"></param>
        /// <param name="page"></param>
        /// <returns></returns>
        #region Update()
        [ActionName("Update")]
        [HttpGet]
        public ActionResult Update(string board_id, string page, BoardRequest boardRequest)
        {
            // 페이지 유지
            if (string.IsNullOrEmpty(page))
                page = "1";
            ViewBag.pageNumber = page;


            // 검색 값 유지 - ViewBag
            if (boardRequest.search_type != null && boardRequest.search_word != null)
            {
                ViewBag.search_type = boardRequest.search_type;
                ViewBag.search_word = boardRequest.search_word;
            }

            BoardDAO dao = new BoardDAO();

            Board board = dao.ReadBoard(int.Parse(board_id));

            return View("Update", board);
        }
        #endregion

        /// <summary>
        /// Update(Board board, BoardRequest boardRequest)
        /// 게시물을 수정하는 액션
        /// HttpPost로 진입한 경우에 수행
        /// </summary>
        /// <param name="board"></param>
        /// <returns></returns>
        #region Update()
        [ActionName("Update")]
        [HttpPost]
        public ActionResult Update(Board board, BoardRequest boardRequest, string page)
        {
            BoardDAO dao = new BoardDAO();
            int result = 0;

            // 페이지 유지
            if (string.IsNullOrEmpty(page))
                page = "1";

            ViewBag.pageNumber = page;

            // Model 유효성 검증
            if (!ModelState.IsValid)
            {
                // Update View 에서는 기존 입력된 데이터가 있어야하므로 다시 Read 하여 Return 및 유효성을 검증한다.
                board = dao.ReadBoard(board.board_id);
                return View(board);
            }

            // 유효하다면 수정 ▼
            result = dao.UpdateBoard(board);

            if (result > 0)
                return RedirectToAction("List", boardRequest);
            else
                return View("Errors");


        }
        #endregion


        /// <summary>
        /// Delete(string board_id)
        /// 게시물을 삭제하는 액션
        /// HttpPost로 진입한 경우에 수행(Ajax)
        /// </summary>
        /// <param name="board_id"></param>
        /// <returns></returns>
        #region Delete()
        [ActionName("Delete")]
        [HttpPost]
        public ActionResult Delete(string board_id)
        {
            BoardDAO dao = new BoardDAO();

            int result = dao.DeleteBoard(int.Parse(board_id));

            if(result > 0)
                return RedirectToAction("List");

            return View("Errors");
        }
        #endregion

    }
}

MostiSubject_MVC_Board/Views/Board/Create.cshtml
@model MostiSubject_MVC_Board.Models.Board
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@* 페이지 기본 정보 *@
<div>
    <h3>
        게시물 작성
    </h3>
    <hr />
</div>

@* 입력 폼 *@
<div style="width:400px;">
    @using (Html.BeginForm("Create", "Board", FormMethod.Post, new { @enctype = "multipart/form-data" }))
    {

        @Html.AntiForgeryToken();
        @Html.ValidationSummary(true, "", new { @class = "text-danger" });


        <div class="form-group">
            @Html.LabelFor(model => model.title)
            @Html.EditorFor(model => model.title, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.title, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.content)
            @Html.TextAreaFor(model => model.content, new { @class = "form-control", rows = "20" })
            @Html.ValidationMessageFor(model => model.content, "", new { @class = "text-danger" })

        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.u_id)
            @Html.EditorFor(model => model.u_id, new { htmlAttributes = new { @class = "form-control", @readonly = "readyonly", @Value = "skkim@mostisoft.com" } })

        </div>

        <div class="form-group">
            @Html.TextBoxFor(model => model.files, "", new { type = "file" }) <br />
        </div>

        <div style="text-align:center; display:inline-block;">
            <input type="submit" value="작성" class="btn btn-primary" />
        </div>



    }

    @* 돌아가기 *@
    <div class="form-group">
        @Html.ActionLink("돌아가기", "List", "Board", new { search_type = ViewBag.search_type, search_word = ViewBag.search_word, page = ViewBag.pageNumber }, null)
    </div>






</div>

MostiSubject_MVC_Board/Views/Board/Detail.cshtml
@model MostiSubject_MVC_Board.Models.BoardResponse
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link href="~/Content/PagedList.css" rel="stylesheet"/ type="text/css">

@* javascript *@
<script type="text/javascript">

    // submit 전 삭제여부 확인
    function delCheck()
    {
        var ask = confirm("정말 삭제하시겠습니까?");
        if (!ask)
        {
            alert("취소되었습니다.");
            return false;
        }

        return true;
    }

</script>


@* 페이지 기본 정보 *@
<div>
    <h3>
        게시물 조회
    </h3>
    <hr />
</div>

@* 입력 폼 *@
<div style="width:400px;">



        <div class="form-group">
            <h4><span class="label label-default"> 제목 </span></h4>
            <input type="text" value="@Model.boardDetail.title" class="form-control" readonly="readonly" style="background-color:white;" />
        </div>

        <div class="form-group">
            <h4><span class="label label-default">내용</span></h4>
            <textarea rows="30" class="form-control" readonly="readonly" style="background-color:white; -moz-appearance:none; resize:none;">@Model.boardDetail.content</textarea>
        </div>

        <div class="form-group">
            <h4><span class="label label-default">작성자</span></h4>
            <input type="text" value="@Model.boardDetail.u_id" class="form-control" readonly="readonly"/>
        </div>

        <div class="form-group">

            <h4><span class="label label-default">파일</span></h4>

            @using (Html.BeginForm("Detail", "Board", FormMethod.Post))
            {
                <input type="hidden" name="fileName" id="fileName" value="@Model.boardDetail.fileName" />
                if (Model.boardDetail.fileName == "업로드된 파일 없음")
                {
                    <span class="form-control" style="width:280px; background-color:darkgrey;">@Model.boardDetail.fileName</span>
                    <input type="submit" value="다운로드" class="form-control" disabled="disabled">
                }
                else if (Model.boardDetail.fileName == "")
                {
                    <span class="form-control" style="width:280px; background-color:darkgrey;">업로드된 파일 없음</span>
                    <input type="submit" value="다운로드" class="form-control" disabled="disabled">
                }
                else
                {
                    <span class="form-control" style="width:280px;">@Model.boardDetail.fileName</span>
                    <input type="submit" value="다운로드" class="form-control">
                }

            }
        </div>
        
        <div class="form-group">
            @* 수정 *@
            @Html.ActionLink("수정", "Update", "Board", new { board_id = Model.boardDetail.board_id, page = Model.page, search_type = ViewBag.search_type, search_word = ViewBag.search_word}, null)

            @* 삭제 *@
            @using (Html.BeginForm("Delete", "Board", FormMethod.Post, new { @style = "display:inline;", @onsubmit = "return delCheck()" }))
            {
                <input type="hidden" value="@Model.boardDetail.board_id" id="board_id" name="board_id" />
                <input type="submit" value="삭제" style="background-color:white; padding:0; border:none;" class="text-danger" />
            }

            <br />
            @* 돌아가기 *@
          
            @Html.ActionLink("돌아가기", "List", "Board", new { search_type = ViewBag.search_type, search_word = ViewBag.search_word, page = ViewBag.pageNumber }, null)

        </div>

</div>

MostiSubject_MVC_Board/Views/Board/Errors.cshtml
@{
    Layout = "~/Views/Shared/Error.cshtml";
}

MostiSubject_MVC_Board/Views/Board/List.cshtml
@model PagedList.IPagedList<MostiSubject_MVC_Board.Models.Board>

@using PagedList.Mvc;
@using MostiSubject_MVC_Board.ControlHelpers;

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}




<style type="text/css">
    .leaves {
        width: 1000px;
    }

        .leaves th {
            padding-bottom: 1em;
        }

            .leaves th.board_rownum {
                width: 5%;
            }

            .leaves th.board_title {
                width: 20%;
            }

            .leaves th.board_date {
                width: 20%;
            }

            .leaves th.board_writer {
                width: 20%;
            }
            .leaves th.linkBtn {
                width:10%;
            }
        .leaves td {
        }
    .search_form {
        text-align:center;
    }
    #search_type {
        display:inline;
        width:100px;
        
        
    }
    #search_word {
        display:inline;
    }
</style>

<link href="~/Content/PagedList.css" rel="stylesheet" / type="text/css">

@* jquery CDN *@
<script type="text/javascript" src="https://code.jquery.com/jquery-3.6.0.min.js"></script>


<script type="text/javascript">
    function Delete(id)
    {
        var delCheck = confirm("해당 게시물을 삭제하시겠습니까??");
        if (!delCheck)
        {
            alert("취소되었습니다.");
            return;
        }
        
        // 삭제 ajax 처리
        $.ajax({

            data: {
                board_id: id
            }
            , url: "Delete"
            , type: "POST"
            , success: function (data) {

                var board_list_html = $(data).find("div.board_list").html();
                $("div.board_list").html(board_list_html);

            }
            , error: function (xhr, status, error) {
                alert(error.toString());
            }

        });
    }

    function searching()
    {
        var search_type = $("#search_type").val();
        var search_word = $("#search_word").val();
        

        $.ajax({

            type:"GET"
            , data:{
                search_type: search_type
                , search_word: search_word
                
            }
            , url:"Search"
            , success:function (data) {
                var board_list_html = $(data).find("div.board_list").html();
                var search_form_html = $(data).find("div.search_form").html();
                var container_html = $(data).find("div#container").html();


                $("div.board_list").html(board_list_html);
                $("div.search_form").html(search_form_html);
                $("div#container").html(container_html);
            }
            , error: function (xhr, status, error) {
              
                //alert(error.toString());
            }

        });
    }
</script>
<div class="search_form">
@* 페이지 기본 정보 영역 *@
<div>
    <h3>
        게시물 목록
    </h3>
    <hr />
</div>

@* 검색하는 영역 *@

    
    <div class="form-group">


        <select id="search_type" class="form-control">
            @if (ViewBag.search_type != null)
            {
                if (ViewBag.search_type == "BOARD_TITLE")
                {
                    <option value="BOARD_TITLE" selected="selected">Title</option>
                    <option value="U_ID">Email</option>
                    <option value="BOARD_CONTENT">Content</option>
                }
                else if (ViewBag.search_type == "U_ID")
                {
                    <option value="U_ID" selected="selected">Email</option>
                    <option value="BOARD_TITLE">Title</option>
                    <option value="BOARD_CONTENT">Content</option>
                }
                else if (ViewBag.search_type == "BOARD_CONTENT")
                {
                    <option value="BOARD_CONTENT" selected="selected">Content</option>
                    <option value="BOARD_TITLE">Title</option>
                    <option value="U_ID">Email</option>
                }

            }
            else
            {
                <option value="BOARD_TITLE">Title</option>
                <option value="U_ID">Email</option>
                <option value="BOARD_CONTENT">Content</option>
            }
        </select>

        @if (ViewBag.search_word != null)
        {
            <input type="text" class="form-control" id="search_word" value="@ViewBag.search_word" />
        }
        else
        {
            <input type="text" class="form-control" placeholder="검색어입력" id="search_word" />
        }

        <input type="button" id="searchBtn" value="검색" class="btn btn-success" onclick="searching()" />

        <hr />
    </div>
</div>

@* 게시물 리스트가 출력되는 영역 *@
<div class="board_list">
    <table class="leaves">
        <tr>
            <th class="board_rownum">
                번호
            </th>
            <th class="board_title">
                제목
            </th>
            <th class="board_writer">
                작성자
            </th>
            <th class="board_date">
                작성일
            </th>
            <th class="linkBtn">
                관리
            </th>
        </tr>


        @* 모델에서 출력하는 내용  *@
        @{

            foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.rownum)
                    </td>
                    <td>
                        @if (item.title.Length > 15)
                        {
                            item.title = item.title.Substring(0, 15) + "...";
                        }
                        @Html.DisplayFor(modelItem => item.title)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.u_id)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.board_date)
                    </td>
                    <td>
                        @Html.ActionLink(
                   "상세"                                                        // linkText
                   , "Detail"                                                    // actionName
                   , "Board"                                                     // controller
                   , new { board_id = item.board_id, page = ViewBag.pageNumber, search_type=ViewBag.search_type, search_word=ViewBag.search_word } // routeValue
                   , null                                                        // htmlAttribute
                   )
                        |
                        @Html.ActionLink(
                   "수정"
                   , "Update"
                   , "Board"
                   , new { board_id = item.board_id, page = ViewBag.pageNumber, search_type = ViewBag.search_type, search_word = ViewBag.search_word }
                   , null
                   )
                        |
                        <button value="@item.board_id"
                                onclick="Delete(@item.board_id)"
                                style="background-color:white;
                                       border:none;
                                       padding:0;">
                            <span class="text-danger"> 삭제 </span>
                        </button>

                    </td>
                </tr>
                }
        }

    </table>

    @* 숨겨진 pageNumber *@
    <input type="hidden" value="@ViewBag.pageNumber" id="pageNum"/> 
    @* 페이지 *@
    <div style="text-align:center; display:inline;">
        @Html.PagedListPager(Model, page => Url.Action("List", new { page, search_type = ViewBag.search_type, search_word = ViewBag.search_word }  ))
    </div>

   
</div>

MostiSubject_MVC_Board/Views/Board/Update.cshtml
@model MostiSubject_MVC_Board.Models.Board
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@* 페이지 기본 정보 *@
<div>
    <h3>
        게시물 수정
    </h3>
    <hr />
</div>

@* 입력 폼 *@
<div style="width:400px;">
    @using (Html.BeginForm("Update", "Board", FormMethod.Post, new { @enctype = "multipart/form-data" }))
    {

        @Html.AntiForgeryToken();
        @Html.ValidationSummary(true, "", new { @class = "text-danger" });


        <div class="form-group">
            @Html.LabelFor(model => model.title)
            @Html.EditorFor(model => model.title, new { htmlAttributes = new { @class = "form-control", @Value = Model.title } })
            @Html.ValidationMessageFor(model => model.title, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.content)
            @Html.TextAreaFor(model => model.content, new { @class = "form-control", rows = "20", @Value = Model.content })
            @Html.ValidationMessageFor(model => model.content, "", new { @class = "text-danger" })

        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.u_id)
            @Html.EditorFor(model => model.u_id, new { htmlAttributes = new { @class = "form-control", @readonly = "readyonly", @Value = "skkim@mostisoft.com" } })

        </div>

        <div class="form-group">
            @if (Model.fileName == "업로드된 파일 없음")
            {
                @Html.TextBoxFor(model => model.files, "", new { type = "file" }) <br />
            }
            else if (Model.fileName == "")
            {
                @Html.TextBoxFor(model => model.files, "", new { type = "file" }) <br />
            }
            else
            {
                <span id="fileName" class="form-control" style="width:280px; background-color:darkgrey;">@Model.fileName</span>

            }
        </div>

        <div style="text-align:center; display:inline-block;">
            @*
                숨겨진 데이터들
                게시물 id
                검색조건(타입)
                검색어
                페이지번호
            *@
            <input type="hidden" value="@Model.board_id" id="board_id" name="board_id" />
            <input type="hidden" value="@ViewBag.search_type" id="search_type" name="search_type" />
            <input type="hidden" value="@ViewBag.search_word" id="search_word" name="search_word" />
            <input type="hidden" value="@ViewBag.pageNumber" id="page" name="page" />
            <input type="submit" value="수정" class="btn btn-primary" />
        </div>
        <br /><br />

        @Html.ActionLink("돌아가기", "List", "Board", new { search_type = ViewBag.search_type, search_word = ViewBag.search_word, page = ViewBag.pageNumber }, null)
    }

</div>